### ISSUE TITLE
Float Clearing Needs Work

### ISSUE THREAD

**Issue by thezenmonkey** [ladieslearningcode/llc-css-fundamentals#6]
The JSFiddle float clearing section caused confusion. Most of the learners had trouble mentally moving between their code and jsfiddle. Kind of a 'why are we doing this?' It may work better if they break their site more then move to jsfiddle to how the fix. I went off script a lot in thatsection to show them differnt things that happen when you change float properties. Basically more examples in the project code.

**Comment by christinatruong** [comment]
The JSFiddle was used b/c common feedback from learners is they find flipping back and forth between editor & browser to be confusing. JSFiddle allows the user to see the code and the changes all in the same screen. The instructor should go through the example line by line with the class to explain what happens when you float and to demonstrate the difference between clearing the float & using clearfix.

Though the clearfix class shouldn't have already been there in the example so that's been updated.
